### PR TITLE
Add FindSDL2

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi,

Add FindSDL2 to fix this issue https://github.com/eezstreet/OpenD2/issues/34  Please review the patch.

Thanks,
Leslie Zhai

### CODE REVIEW

**Comment by eezstreet** [comment]
Can anyone else reproduce the original issue?

**Comment by xiangzhai** [comment]
Hi @eezstreet 

Thanks for your response!

Old Linux distribution, for example, Fedora Core 21, is easy to reproduce the issue.

Thanks,
Leslie Zhai

**Comment by xiangzhai** [comment]
Hi @eezstreet 

I will fix the conflict next week.  Happy weekend!

Cheers,
Leslie Zhai

**Comment by xiangzhai** [comment]
PING

**Pull request closed without merging**
